<?php

namespace Gin\Erp\NodesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NativeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NativeTypeRepository extends EntityRepository
{
    public function findAll() {
        return $this->findBy(array(), array('caption'=>'asc'));
    }
   
}
