<?php

namespace Gin\Erp\NodesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeAttributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeAttributeRepository extends EntityRepository
{
}
