<?php

namespace Gin\Erp\NodesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
    
    /**
     * 
     * @param \Gin\Erp\NodesBundle\Entity\Node $node
     */
    public function createNode($node) {
        $em=$this->getEntityManager();
        $em->persist($node);
        $em->flush();
        $this->createNodeTable($node);
    }
    
    /**
     * 
     * @param \Gin\Erp\NodesBundle\Entity\Node $node
     */
    protected function createNodeTable($node) {
        $em=$this->getEntityManager();
        $con=$em->getConnection();
        
        $realTableName='node_' . $node->getName();
//        $con->exec('create table '.$realTableName. '()');
        
        $table=new \Doctrine\DBAL\Schema\Table($realTableName);
        $table->addColumn('id', 'integer');
        // IDs no automáticos por db, se generarán en la app (max+1)
        $table->setPrimaryKey(array('id'));
        
        $con->getSchemaManager()->createTable($table);
    }
    
}
